<?php

namespace Tests;

use PHPUnit\Framework\TestCase as UnitTestCase;

abstract class TestCase extends UnitTestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}